server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/book}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
    liquibase-schema: public
    user: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}

